# Generated by Django 3.2.5 on 2021-07-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesdetail',
            name='Code',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seriesdetail',
            name='Name',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
